Repository MTVS-third-study/adregamdi, pull requests merged in 2023-07, with the labels that each got.

#65 Feature/지도 이동 범위 제한(#4)
  src/main/resources/static/css/schedule.css
  src/main/resources/templates/main.html
  src/main/resources/templates/schedule.html
Labels: 📬 API, ✨ Feature

#69 Feature/entity/place
  build.gradle
  src/main/java/com/ohgiraffers/adregamdi/blacklist/domain/entity/BlackList.java
  src/main/java/com/ohgiraffers/adregamdi/blacklist/domain/entity/BlackListDate.java
  src/main/java/com/ohgiraffers/adregamdi/blacklist/domain/entity/BlackListMemberNo.java
  src/main/java/com/ohgiraffers/adregamdi/blacklist/domain/entity/test.java
  src/main/java/com/ohgiraffers/adregamdi/blacklist/domain/repository/BlackListRepository.java
  src/main/java/com/ohgiraffers/adregamdi/blacklist/infra/repository/BlackListJPARepository.java
  src/main/java/com/ohgiraffers/adregamdi/blacklist/infra/repository/BlackListMyBatisRepository.java
  src/main/java/com/ohgiraffers/adregamdi/blacklist/query/application/repository/BlackListQueryRepository.java
  src/main/java/com/ohgiraffers/adregamdi/blacklist/query/application/service/BlackListFindService.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/aggregate/entity/Place.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/aggregate/entity/test.java
  src/main/resources/templates/schedule.html
Labels: ✨ Feature

#79 Page/main
  src/main/java/com/ohgiraffers/adregamdi/main/MainController.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/service/PlaceService.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/service/test.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/domain/entity/Place.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/infra/repository/PlaceRepository.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/infra/repository/test.java
  src/main/resources/static/css/main.css
  src/main/resources/static/images/Adregamdi.png
  src/main/resources/static/images/goodlogo.png
  src/main/resources/static/images/jejuIsland.png
  src/main/resources/static/images/volcano.png
  src/main/resources/static/images/volcanoBoom.png
  src/main/resources/templates/main.html
  src/main/resources/templates/myPage.html
Labels: 🎨 Html&css

#82 openAPI 데이터 parsing 기능 구현
  build.gradle
  src/main/java/com/ohgiraffers/adregamdi/place/command/application/controller/DataController.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/application/service/DataService.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/application/service/test.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/service/DataDomainService.java
  src/main/resources/static/css/schedule.css
  src/main/resources/static/js/kakaomap.js
  src/main/resources/templates/schedule.html
  src/test/java/com/ohgiraffers/adregamdi/AdreGamdiApplicationTests.java
Labels: 📬 API

#83 Page/main
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/repository/PlaceRepository.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/infra/repository/PlaceRepository.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/infra/service/PlaceService.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/infra/repository/PlaceRepository.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/controller/OAuthController.java
  src/main/resources/static/css/main.css
  src/main/resources/static/images/airplane.png
  src/main/resources/static/images/jejuIsland.png
  src/main/resources/static/images/volcano.png
  src/main/resources/static/images/volcanoBoom.png
  src/main/resources/templates/main.html
  src/test/java/com/ohgiraffers/adregamdi/report/application/controller/test.java
  src/test/java/com/ohgiraffers/adregamdi/report/application/dto/test.java
  src/test/java/com/ohgiraffers/adregamdi/report/application/service/test.java
  src/test/java/com/ohgiraffers/adregamdi/report/domain/entity/reportEntity.java
  src/test/java/com/ohgiraffers/adregamdi/report/domain/repository/test.java
  src/test/java/com/ohgiraffers/adregamdi/report/domain/service/test.java
  src/test/java/com/ohgiraffers/adregamdi/report/infra/repository/test.java
  src/test/java/com/ohgiraffers/adregamdi/report/infra/service/test.java
  src/test/java/com/ohgiraffers/adregamdi/review/application/controller/test.java
  src/test/java/com/ohgiraffers/adregamdi/review/application/dto/test.java
  src/test/java/com/ohgiraffers/adregamdi/review/application/service/CreateReviewServiceTests.java
  src/test/java/com/ohgiraffers/adregamdi/review/domain/entity/reviewEntity.java
  src/test/java/com/ohgiraffers/adregamdi/review/domain/repository/test.java
  src/test/java/com/ohgiraffers/adregamdi/review/domain/service/test.java
  src/test/java/com/ohgiraffers/adregamdi/review/infra/repository/test.java
  src/test/java/com/ohgiraffers/adregamdi/review/infra/service/test.java
Labels: 🎨 Html&css

#85 로그아웃 기능 (#55)
  .github/workflows/gradle.yml
  src/main/java/com/ohgiraffers/adregamdi/review/application/controller/ReviewController.java
  src/main/java/com/ohgiraffers/adregamdi/review/application/dto/ReviewDTO.java
  src/main/java/com/ohgiraffers/adregamdi/review/application/service/ReviewService.java
  src/main/java/com/ohgiraffers/adregamdi/review/domain/aggregate/entity/Review.java
  src/main/java/com/ohgiraffers/adregamdi/review/domain/repository/ReviewRepository.java
  src/main/java/com/ohgiraffers/adregamdi/review/domain/service/CreateReviewService.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/controller/OAuthController.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/controller/UserController.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/service/OAuthService.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/service/UserService.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/domain/aggregate/entity/User.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/domain/repository/UserRepository.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/domain/service/KakaoDomainService.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/domain/service/UserDomainService.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/infrastructure/repository/UserInfraRepository.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/infrastructure/service/KakaoDomainServiceImpl.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/infrastructure/service/UserDomainServiceImpl.java
  src/main/java/com/ohgiraffers/adregamdi/user/query/application/service/KakaoQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/user/query/application/service/UserQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/user/query/infrastructure/repository/UserFindInfraRepository.java
  src/main/resources/templates/kakao/loginForm.html
  src/main/resources/templates/main.html
  src/main/resources/templates/registReview.html
Labels: ✨ Feature

#86 Feature/review
  src/main/java/com/ohgiraffers/adregamdi/review/application/controller/ReviewController.java
  src/main/java/com/ohgiraffers/adregamdi/review/application/dto/ReviewDTO.java
  src/main/java/com/ohgiraffers/adregamdi/review/application/service/ReviewService.java
  src/main/java/com/ohgiraffers/adregamdi/review/domain/aggregate/entity/Review.java
  src/main/java/com/ohgiraffers/adregamdi/review/domain/aggregate/entity/ReviewPlaceNo.java
  src/main/java/com/ohgiraffers/adregamdi/review/domain/service/CreateReviewService.java
  src/main/resources/templates/registReview.html
Labels: ✨ Feature

#87 회원탈퇴 기능
  .github/workflows/gradle.yml
  src/main/java/com/ohgiraffers/adregamdi/main/MainController.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/controller/OAuthController.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/controller/UserController.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/dto/KakaoUserDTO.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/dto/UserDTO.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/service/OAuthService.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/service/UserService.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/domain/aggregate/entity/User.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/domain/aggregate/vo/UserVO.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/domain/repository/UserRepository.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/infrastructure/service/KakaoDomainServiceImpl.java
  src/main/java/com/ohgiraffers/adregamdi/user/query/application/controller/test.java
  src/main/java/com/ohgiraffers/adregamdi/user/query/application/service/UserQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/user/query/infrastructure/repository/UserQueryRepository.java
  src/main/java/com/ohgiraffers/adregamdi/user/query/infrastructure/service/KakaoQueryInfraService.java
  src/main/resources/templates/main.html
  src/main/resources/templates/myPage.html
  src/main/resources/templates/user/deleteForm.html
  src/main/resources/templates/user/myPage.html
  src/test/java/com/ohgiraffers/adregamdi/UserTests.java
Labels: ✨ Feature

#89 회원전체 조회기능 (#8)
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/dto/UserDTO.java
  src/main/resources/static/css/admin.css
  src/main/resources/static/css/kakao.css
  src/main/resources/static/css/schedule.css
  src/main/resources/static/images/blackLike.png
  src/main/resources/static/images/home_house_icon.png
  src/main/resources/static/images/images.jpg
  src/main/resources/static/images/info.png
  src/main/resources/static/images/marker.png
  src/main/resources/static/images/phone.png
  src/main/resources/static/images/plus.png
  src/main/resources/static/images/reviewAdd.png
  src/main/resources/static/images/schedule_icon.png
  src/main/resources/static/images/siren.png
  src/main/resources/static/images/whiteLike.png
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/shcedule.js
  src/main/resources/templates/adminPage.html
  src/main/resources/templates/main.html
  src/main/resources/templates/schedule.html
Labels: ✨ Feature

#92 카카오 로그인 버그 수정
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/dto/UserDTO.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/service/OAuthService.java
  src/main/java/com/ohgiraffers/adregamdi/user/query/application/service/UserQueryService.java
  src/main/resources/templates/user/myPage.html
Labels: 🐞 BugFix

#93 Feature/save db
  .github/workflows/gradle.yml
  src/main/java/com/ohgiraffers/adregamdi/place/command/application/service/DataService.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/aggregate/entity/Category.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/aggregate/entity/City.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/aggregate/entity/Dong.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/aggregate/entity/Place.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/aggregate/entity/PlaceTags.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/aggregate/entity/Tag.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/aggregate/vo/Address.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/aggregate/vo/CategoryVO.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/aggregate/vo/CityVO.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/aggregate/vo/Coordinate.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/aggregate/vo/CoordinateVO.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/aggregate/vo/DongVO.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/aggregate/vo/PlaceVO.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/aggregate/vo/TagVO.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/repository/CategoryRepository.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/repository/CityRepository.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/repository/DongRepository.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/repository/PlaceRepository.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/repository/PlaceTagsRepository.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/repository/TagRepository.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/service/DataDomainService.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/service/PlaceAPIService.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/service/PlaceService.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/infra/repository/PlaceInfraRepository.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/infra/service/PlaceInfraAPIService.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/infra/service/PlaceService.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/application/service/DataQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/application/service/test.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/domain/entity/Place.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/infra/repository/CategoryQueryRepository.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/infra/repository/CityQueryRepository.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/infra/repository/DongQueryRepository.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/infra/repository/PlaceQueryRepository.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/infra/repository/PlaceRepository.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/infra/repository/TagQueryRepository.java
  src/test/java/com/ohgiraffers/adregamdi/AdreGamdiApplicationTests.java
  src/test/java/com/ohgiraffers/adregamdi/TagQueryRepositoryTests.java
  src/test/java/com/ohgiraffers/adregamdi/place/command/application/service/DataServiceTest.java
  src/test/java/com/ohgiraffers/adregamdi/place/query/application/service/DataQueryServiceTest.java
Labels: ✨ Feature

#95 refactor : @Transactional 위치 변경
  src/main/java/com/ohgiraffers/adregamdi/place/command/application/service/DataService.java
  src/test/java/com/ohgiraffers/adregamdi/TagQueryRepositoryTests.java
Labels: 🔨 Refactor

#99 스케줄 정보 insert 기능 구현
  src/main/java/com/ohgiraffers/adregamdi/place/command/application/service/DataService.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/aggregate/entity/Place.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/application/controller/ScheduleController.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/application/controller/test.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/application/dto/ScheduleDTO.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/application/dto/test.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/application/service/ScheduleDTOEntityMapper.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/application/service/ScheduleService.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/application/service/test.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/domain/aggregate/entity/Schedule.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/domain/aggregate/vo/Day.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/domain/aggregate/vo/ScheduleDayVO.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/domain/aggregate/vo/ScheduleUserNoVO.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/domain/aggregate/vo/UserNo.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/domain/repository/ScheduleRepository.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/domain/service/ScheduleDomainService.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/domain/service/test.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/query/application/dto/ScheduleQueryDTO.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/query/application/service/ScheduleQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/query/application/service/test.java
  src/main/java/com/ohgiraffers/adregamdi/user/query/infrastructure/repository/UserQueryRepository.java
  src/test/java/com/ohgiraffers/adregamdi/AdreGamdiApplicationTests.java
  src/test/java/com/ohgiraffers/adregamdi/place/query/application/service/DataQueryServiceTest.java
  src/test/java/com/ohgiraffers/adregamdi/schedule/command/application/service/ScheduleServiceTest.java
Labels: ✨ Feature

#101 불필요 태그들 parse 제거 및 유효성 로직 구현
  src/main/java/com/ohgiraffers/adregamdi/place/command/application/service/DataService.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/service/DataDomainService.java
  src/test/java/com/ohgiraffers/adregamdi/AdreGamdiApplicationTests.java
  src/test/java/com/ohgiraffers/adregamdi/place/command/domain/service/DataDomainServiceTest.java
Labels: 🐞 BugFix

#102 Update gradle.yml
  .github/workflows/gradle.yml
Labels: 🐞 BugFix

#104 bugfix: testCode 수리
  src/main/java/com/ohgiraffers/adregamdi/place/command/application/service/DataService.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/application/dto/ScheduleDTO.java
Labels: 🐞 BugFix

#106 mybatis mapping 초기 설정, 장소 키워드로 검색 기능 개발
  build.gradle
  src/main/java/com/ohgiraffers/adregamdi/common/MybatisConfiguration.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/service/PlaceAPIService.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/infra/service/PlaceInfraAPIService.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/application/service/DataQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/application/service/PlaceService.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/domain/entity/SearchPlace.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/infra/repository/PlaceMapper.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/infra/repository/PlaceRepository.java
  src/main/resources/application.properties
  src/main/resources/config/mybatis-config.xml
  src/main/resources/mybatis/mappers/PlaceMapper.xml
  src/main/resources/static/css/main.css
  src/test/java/com/ohgiraffers/adregamdi/place/PlaceQueryTests.java
  src/test/java/com/ohgiraffers/adregamdi/place/query/application/service/PlaceServiceTests.java
Labels: ✨ Feature, ⚙ Setting, ✅ Test

#111 thymeleaf수정
  src/main/resources/templates/schedule.html
Labels: 🐞 BugFix

#115 bugfix : MySQL url 설정 변경
  src/main/resources/application.properties
Labels: 🐞 BugFix, ⚙ Setting

#116 회원 탈퇴 버그 픽스 (#107)
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/controller/OAuthController.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/controller/UserController.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/dto/UserDTO.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/service/OAuthService.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/service/UserService.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/domain/repository/UserRepository.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/domain/service/KakaoDomainService.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/domain/service/UserDomainService.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/infrastructure/service/KakaoDomainServiceImpl.java
  src/main/java/com/ohgiraffers/adregamdi/user/query/application/service/KakaoQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/user/query/infrastructure/repository/UserQueryRepository.java
  src/main/java/com/ohgiraffers/adregamdi/user/query/infrastructure/service/KakaoQueryInfraService.java
  src/main/resources/templates/kakao/end.html
  src/main/resources/templates/kakao/loginForm.html
  src/main/resources/templates/main.html
Labels: 🐞 BugFix

#121 로그인 버그 수정
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/controller/OAuthController.java
  src/main/resources/templates/main.html
  src/main/resources/templates/user/myPage.html
Labels: 🐞 BugFix

#126 유저 DB 중첩 버그 수정
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/service/OAuthService.java
  src/main/resources/templates/main.html
Labels: 🐞 BugFix

#129 카카오 로그인 버튼 수정
  .github/workflows/gradle.yml
  src/main/java/com/ohgiraffers/adregamdi/user/command/domain/aggregate/entity/User.java
  src/main/resources/static/images/kakao_login_large_narrow.png
  src/main/resources/static/images/kakao_login_medium_narrow.png
  src/main/resources/templates/main.html
Labels: 🔨 Refactor

#132 관리자페이지,스케주페이지수정
  src/main/java/com/ohgiraffers/adregamdi/category/query/application/service/CategoryQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/category/query/infra/repository/CategoryQueryRepository.java
  src/main/java/com/ohgiraffers/adregamdi/cityanddong/query/application/service/CityQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/cityanddong/query/application/service/DongQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/cityanddong/query/infra/repository/CityQueryRepository.java
  src/main/java/com/ohgiraffers/adregamdi/cityanddong/query/infra/repository/DongQueryRepository.java
  src/main/java/com/ohgiraffers/adregamdi/data/command/application/service/DataService.java
  src/main/java/com/ohgiraffers/adregamdi/data/command/domain/service/DataAPIService.java
  src/main/java/com/ohgiraffers/adregamdi/data/command/infra/service/DataInfraAPIService.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/application/dto/PlaceTagsDTO.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/application/service/PlaceTagsService.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/aggregate/entity/PlaceTags.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/repository/PlaceTagsRepository.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/application/controller/PlaceQueryController.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/application/dto/ResponsePlaceDTO.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/application/dto/ResponsePlaceTagsDTO.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/application/dto/test.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/application/service/PlaceQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/application/service/PlaceTagsQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/infra/repository/PlaceQueryRepository.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/infra/repository/PlaceTagsQueryRepository.java
  src/main/java/com/ohgiraffers/adregamdi/tag/command/application/dto/TagDTO.java
  src/main/java/com/ohgiraffers/adregamdi/tag/command/application/dto/test.java
  src/main/java/com/ohgiraffers/adregamdi/tag/command/application/service/TagService.java
  src/main/java/com/ohgiraffers/adregamdi/tag/query/application/service/TagQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/tag/query/infra/repository/TagQueryRepository.java
  src/main/resources/static/css/admin.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/schedule.css
  src/main/resources/static/images/list.png
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/shcedule.js
  src/main/resources/templates/adminPage.html
  src/main/resources/templates/main.html
  src/main/resources/templates/schedule.html
  src/test/java/com/ohgiraffers/adregamdi/cityanddong/query/application/service/CityQueryServiceTest.java
  src/test/java/com/ohgiraffers/adregamdi/data/command/application/service/DataServiceTest.java
Labels: 🎨 Html&css, ✨ Feature

#136 Refactor/entity
  src/main/java/com/ohgiraffers/adregamdi/category/command/application/service/CategoryService.java
  src/main/java/com/ohgiraffers/adregamdi/category/command/domain/aggregate/entity/Category.java
  src/main/java/com/ohgiraffers/adregamdi/cityanddong/command/application/service/CityService.java
  src/main/java/com/ohgiraffers/adregamdi/cityanddong/command/application/service/DongService.java
  src/main/java/com/ohgiraffers/adregamdi/cityanddong/command/domain/aggregate/entity/City.java
  src/main/java/com/ohgiraffers/adregamdi/cityanddong/command/domain/aggregate/entity/Dong.java
  src/main/java/com/ohgiraffers/adregamdi/cityanddong/query/application/service/DongQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/aggregate/entity/Place.java
  src/main/java/com/ohgiraffers/adregamdi/place/command/domain/aggregate/entity/PlaceTags.java
  src/main/java/com/ohgiraffers/adregamdi/place/query/application/service/PlaceQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/domain/aggregate/entity/Schedule.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/query/application/service/ScheduleQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/tag/command/application/service/TagService.java
  src/main/java/com/ohgiraffers/adregamdi/tag/command/domain/aggregate/entity/Tag.java
  src/main/java/com/ohgiraffers/adregamdi/tag/command/domain/service/TagAPIService.java
  src/main/java/com/ohgiraffers/adregamdi/tag/command/domain/service/test.java
  src/main/java/com/ohgiraffers/adregamdi/tag/command/infra/service/TagInfraAPIService.java
  src/main/java/com/ohgiraffers/adregamdi/tag/query/application/service/TagQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/tag/query/infra/repository/TagQueryRepository.java
  src/main/resources/static/js/shcedule.js
Labels: 🎨 Html&css, 🔨 Refactor, 🥰 Accessibility

#137 유저 엔티티 Builder 관련 수정
  .github/workflows/gradle.yml
  src/main/java/com/ohgiraffers/adregamdi/common/annotation/DomainService.java
  src/main/java/com/ohgiraffers/adregamdi/common/annotation/InfraService.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/dto/KakaoUserDTO.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/dto/UserDTO.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/service/OAuthService.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/service/UserService.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/domain/aggregate/entity/User.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/domain/aggregate/entity/enumtype/Role.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/domain/service/KakaoDomainService.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/domain/service/UserDomainService.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/infrastructure/service/KakaoDomainServiceImpl.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/infrastructure/service/UserDomainServiceImpl.java
  src/main/java/com/ohgiraffers/adregamdi/user/query/application/service/AdminQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/user/query/application/service/UserQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/user/query/infrastructure/service/KakaoQueryInfraService.java
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/schedule.html
  src/test/java/com/ohgiraffers/adregamdi/schedule/query/application/service/ScheduleQueryServiceTest.java
Labels: 🔨 Refactor

#139 bugfix: 메인 페이지 오타 발견 후 수정
  src/main/resources/templates/main.html
Labels: 🎨 Html&css, 🐞 BugFix

#144 place 비동기 처리, 각종 페이지 수정
  src/main/java/com/ohgiraffers/adregamdi/main/MainController.java
  src/main/resources/static/css/myPage.css
  src/main/resources/static/css/schedule.css
  src/main/resources/static/js/myPage.js
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/adminPage.html
  src/main/resources/templates/main.html
  src/main/resources/templates/myPage.html
  src/main/resources/templates/schedule.html
Labels: 📬 API, 🥰 Accessibility, 💻 CrossBrowsing

#146 검색 기능 비동기 처리
  src/main/java/com/ohgiraffers/adregamdi/place/query/application/controller/PlaceQueryController.java
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/schedule.html
Labels: 📬 API, 🥰 Accessibility, 💻 CrossBrowsing

#147 Bugfix/place issue
  build.gradle
  src/main/java/com/ohgiraffers/adregamdi/user/query/application/service/AdminQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/user/query/infrastructure/repository/AdminRepository.java
  src/main/java/com/ohgiraffers/adregamdi/user/query/infrastructure/repository/JpaAdminRepository.java
  src/main/resources/application-oauth.properties
  src/main/resources/application.properties
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/adminPage.html
Labels: 🐞 BugFix

#148 유저 전체 조회 수정/등급 변경 기능 추가
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/controller/AdminController.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/controller/UserController.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/service/AdminService.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/domain/repository/UserRepository.java
  src/main/java/com/ohgiraffers/adregamdi/user/query/application/service/AdminQueryService.java
Labels: 🔨 Refactor, ✨ Feature

#151 내 일정 가져오기
  src/main/java/com/ohgiraffers/adregamdi/schedule/query/application/controller/ScheduleQueryController.java
  src/main/resources/static/css/schedule.css
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/schedule.html
Labels: 🎨 Html&css, ✨ Feature, 🥰 Accessibility

#154 검색 버그
  src/main/resources/static/js/schedule.js
Labels: 🐞 BugFix

#158 맵api 버그수정
  src/main/resources/templates/schedule.html
Labels: 🐞 BugFix

#159 출발일 도착일 요청 시 여행일 수 반환, RESTAPI로 변경
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/application/controller/ScheduleController.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/application/dto/DayAndNightResponseDTO.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/query/application/controller/ScheduleQueryController.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/query/application/dto/MyScheduleResponseDTO.java
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/scheduleResult.html
  src/test/java/com/ohgiraffers/adregamdi/schedule/query/application/service/ScheduleQueryServiceTest.java
Labels: 🔨 Refactor, ✨ Feature

#160 페이지 수정
  src/main/resources/static/css/schedule.css
  src/main/resources/static/images/back.png
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/schedule.html
Labels: 🐞 BugFix

#162 캘린더 부분 몇박며칭 받아오는 거 수정
  src/main/java/com/ohgiraffers/adregamdi/schedule/query/application/controller/ScheduleQueryController.java
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/schedule.html
Labels: 🔨 Refactor, 🐞 BugFix

#164 카카오프로필,버튼 수정등등 페이지수정
  src/main/resources/static/css/schedule.css
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/schedule.html
Labels: ✨ Feature, 🥰 Accessibility, 💻 CrossBrowsing

#171 일정 이름 설정, 날짜 설정, 일정 추가, 일정 초기화 기능 구현
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/domain/aggregate/vo/ScheduleDayVO.java
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/schedule.html
Labels: 🔨 Refactor, ✨ Feature, 🥰 Accessibility, 🐞 BugFix

#165 제보 페이지 제작
  src/main/java/com/ohgiraffers/adregamdi/suggestion/command/application/controller/SuggestionController.java
  src/main/java/com/ohgiraffers/adregamdi/suggestion/command/application/dto/SuggestionDTO.java
  src/main/java/com/ohgiraffers/adregamdi/suggestion/command/application/service/SuggestionCommandService.java
  src/main/java/com/ohgiraffers/adregamdi/suggestion/command/domain/aggregate/entity/Suggestion.java
  src/main/java/com/ohgiraffers/adregamdi/suggestion/command/domain/aggregate/vo/UserNo.java
  src/main/java/com/ohgiraffers/adregamdi/suggestion/command/infra/repository/SuggestionCommandRepository.java
  src/main/java/com/ohgiraffers/adregamdi/suggestion/query/application/service/SuggestionQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/suggestion/query/infra/repository/SuggestionRepository.java
  src/main/resources/mybatis/mappers/PlaceMapper.xml
  src/main/resources/templates/main.html
  src/main/resources/templates/schedule.html
  src/main/resources/templates/suggestionPage.html
  src/test/java/com/ohgiraffers/adregamdi/suggestion/SuggestionTests.java
Labels: ✨ Feature

#175 bugfix : 저장 버튼 다시 생성
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/schedule.html
Labels: 🐞 BugFix

#177 검색 정규표현식 적용
  src/main/java/com/ohgiraffers/adregamdi/place/query/application/controller/PlaceQueryController.java
  src/main/resources/mybatis/mappers/PlaceMapper.xml
Labels: ✨ Feature

#178 세부 일정 등록 기능
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/command/application/controller/DetailScheduleController.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/command/application/dto/DetailScheduleDTO.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/command/application/service/DetailScheduleService.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/command/domain/aggregate/entity/DetailSchedule.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/command/domain/aggregate/vo/PlaceNo.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/command/domain/aggregate/vo/TotalScheduleNo.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/command/domain/repository/DetailScheduleRepository.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/command/domain/service/DetailScheduleDomainService.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/command/infra/repository/test.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/command/infra/service/test.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/query/application/controller/DetailScheduleQueryController.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/query/application/service/test.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/query/infra/repository/DetailScheduleQueryRepository.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/query/infra/service/test.java
  src/main/java/com/ohgiraffers/adregamdi/placebyschedule/application/controller/test.java
  src/main/java/com/ohgiraffers/adregamdi/placebyschedule/application/dto/test.java
  src/main/java/com/ohgiraffers/adregamdi/placebyschedule/application/service/test.java
  src/main/java/com/ohgiraffers/adregamdi/placebyschedule/domain/aggregate/entity/PlaceBySchedule.java
  src/main/java/com/ohgiraffers/adregamdi/placebyschedule/domain/aggregate/vo/PlaceNo.java
  src/main/java/com/ohgiraffers/adregamdi/placebyschedule/domain/aggregate/vo/ProcedureSchedule.java
  src/main/java/com/ohgiraffers/adregamdi/placebyschedule/domain/repository/test.java
  src/main/java/com/ohgiraffers/adregamdi/placebyschedule/domain/service/test.java
  src/main/java/com/ohgiraffers/adregamdi/placebyschedule/infra/repository/test.java
  src/main/java/com/ohgiraffers/adregamdi/placebyschedule/infra/service/test.java
  src/main/java/com/ohgiraffers/adregamdi/report/query/application/controller/test.java
  src/main/java/com/ohgiraffers/adregamdi/report/query/application/service/test.java
  src/main/java/com/ohgiraffers/adregamdi/report/query/infra/repository/test.java
  src/main/java/com/ohgiraffers/adregamdi/report/query/infra/service/test.java
  src/main/java/com/ohgiraffers/adregamdi/review/query/application/controller/ReviewQueryController.java
  src/main/java/com/ohgiraffers/adregamdi/user/query/infrastructure/repository/AdminRepository.java
Labels: ✨ Feature

#180 각종 페이지수정
  src/main/resources/static/css/main.css
  src/main/resources/static/css/schedule.css
  src/main/resources/static/images/marker.png
  src/main/resources/static/images/phone.png
  src/main/resources/static/images/reviewAdd.png
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/schedule.html
Labels: 🔨 Refactor

#181 일정 순서 컬럼 버그 수정
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/command/application/dto/DetailScheduleDTO.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/command/application/service/DetailScheduleService.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/command/domain/aggregate/entity/DetailSchedule.java
Labels: 🐞 BugFix

#182 장소 수정 제안 페이지 디테일 수정
  src/main/java/com/ohgiraffers/adregamdi/suggestion/command/application/controller/SuggestionController.java
  src/main/java/com/ohgiraffers/adregamdi/suggestion/command/application/dto/SuggestionDTO.java
  src/main/java/com/ohgiraffers/adregamdi/suggestion/command/application/service/SuggestionCommandService.java
  src/main/java/com/ohgiraffers/adregamdi/suggestion/command/domain/aggregate/entity/Suggestion.java
  src/main/resources/templates/suggestionPage.html
  src/test/java/com/ohgiraffers/adregamdi/suggestion/SuggestionTests.java
Labels: ✨ Feature

#184 일정 추가 구현
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/command/application/dto/DetailScheduleDTO.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/command/application/service/DetailScheduleService.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/command/domain/aggregate/vo/PlaceNo.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/command/domain/aggregate/vo/TotalScheduleNo.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/application/controller/ScheduleController.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/application/dto/PlaceParseDTO.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/application/dto/ScheduleDTO.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/application/service/ScheduleService.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/domain/exception/test.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/domain/repository/ScheduleRepository.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/domain/service/ScheduleAPIService.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/infra/service/ScheduleInfraAPIService.java
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/schedule.html
  src/test/java/com/ohgiraffers/adregamdi/schedule/command/application/service/ScheduleServiceTest.java
Labels: ✨ Feature

#185 페이지수정
  src/main/resources/static/css/main.css
  src/main/resources/static/css/myPage.css
  src/main/resources/static/css/schedule.css
  src/main/resources/static/images/load.png
  src/main/resources/static/js/myPage.js
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/myPage.html
  src/main/resources/templates/schedule.html
Labels: 🎨 Html&css, 🔨 Refactor

#187 배포용 병합(favicon적용, 각종 오류 수정)
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/controller/AdminController.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/controller/OAuthController.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/controller/UserController.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/dto/KakaoUserDTO.java
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/dto/UserDTO.java
  src/main/java/com/ohgiraffers/adregamdi/user/query/infrastructure/service/KakaoQueryInfraService.java
  src/main/resources/application.properties
  src/main/resources/static/css/myPage.css
  src/main/resources/static/css/schedule.css
  src/main/resources/static/index.html
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/adminPage.html
  src/main/resources/templates/main.html
  src/main/resources/templates/myPage.html
  src/main/resources/templates/schedule.html
  src/main/resources/templates/suggestionPage.html
  src/main/resources/templates/user/deleteForm.html
  src/main/resources/templates/user/myPage.html
  src/test/java/com/ohgiraffers/adregamdi/review/command/application/service/ReviewServiceTests.java
Labels: 🥰 Accessibility, 💻 CrossBrowsing

#190 Feature/update page
  src/main/java/com/ohgiraffers/adregamdi/user/command/application/controller/UserController.java
  src/main/resources/static/css/myPage.css
  src/main/resources/static/css/schedule.css
  src/main/resources/static/images/close.png
  src/main/resources/static/js/myPage.js
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/myPage.html
  src/main/resources/templates/schedule.html
Labels: 🥰 Accessibility, 🐞 BugFix

#191 유저 피드백 페이지
  src/main/java/com/ohgiraffers/adregamdi/feedback/command/application/controller/FeedbackController.java
  src/main/java/com/ohgiraffers/adregamdi/feedback/command/application/service/FeedbackCommandService.java
  src/main/java/com/ohgiraffers/adregamdi/feedback/command/domain/aggregate/entity/Feedback.java
  src/main/java/com/ohgiraffers/adregamdi/feedback/command/domain/aggregate/vo/UserNo.java
  src/main/java/com/ohgiraffers/adregamdi/feedback/command/infra/repository/FeedbackCommandRepository.java
  src/main/java/com/ohgiraffers/adregamdi/feedback/query/application/dto/FeedbackDTO.java
  src/main/java/com/ohgiraffers/adregamdi/feedback/query/application/service/FeedbackQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/feedback/query/infra/repository/FeedbackRepository.java
  src/main/resources/static/css/feedbackPage.css
  src/main/resources/templates/feedbackPage.html
  src/main/resources/templates/main.html
Labels: 🎨 Html&css, ✨ Feature

#200 Feature/bugfix
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/application/dto/PlaceParseDTO.java
  src/main/resources/static/js/kakaomap.js
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/schedule.html
Labels: 🔨 Refactor, 🐞 BugFix

#202 사용자 피드백 모달창 전환
  src/main/java/com/ohgiraffers/adregamdi/feedback/command/application/controller/FeedbackController.java
  src/main/java/com/ohgiraffers/adregamdi/feedback/command/domain/aggregate/entity/Feedback.java
  src/main/resources/static/css/feedbackPage.css
  src/main/resources/static/css/main.css
  src/main/resources/static/js/main.js
  src/main/resources/templates/feedbackPage.html
  src/main/resources/templates/main.html
Labels: 🎨 Html&css, 🔨 Refactor

#204 리뷰 등록 시 에러메세지 뜨는 버그 수정 및 리뷰 등록 후 모달창 닫히도록 변경
  src/main/java/com/ohgiraffers/adregamdi/review/command/application/controller/ReviewController.java
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/schedule.html
Labels: 🐞 BugFix

#206 장소 요청 페이지
  src/main/resources/static/css/main.css
  src/main/resources/static/css/suggestionPage.css
  src/main/resources/templates/suggestionPage.html
Labels: 🎨 Html&css

#208 Feature/place req page
  src/main/resources/static/css/main.css
  src/main/resources/static/css/myPage.css
  src/main/resources/static/css/review.css
  src/main/resources/static/css/schedule.css
  src/main/resources/static/js/myPage.js
  src/main/resources/static/js/review.js
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/main.html
  src/main/resources/templates/myPage.html
  src/main/resources/templates/schedule.html
Labels: 🔨 Refactor, 🐞 BugFix

#209 장소 요청 페이지 재매핑
  src/main/java/com/ohgiraffers/adregamdi/suggestion/command/application/controller/SuggestionController.java
  src/main/resources/templates/myPage.html
  src/main/resources/templates/suggestionPage.html
Labels: 🔨 Refactor

#213 Feature/delete my schedule
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/command/application/dto/DetailScheduleDTO.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/command/application/service/DetailScheduleService.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/command/domain/repository/DetailScheduleRepository.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/query/application/controller/DetailScheduleQueryController.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/query/application/service/DetailScheduleQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/query/application/service/test.java
  src/main/java/com/ohgiraffers/adregamdi/detailschedule/query/infra/repository/DetailScheduleQueryRepository.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/application/controller/ScheduleController.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/application/dto/DeleteScheduleDTO.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/application/service/ScheduleService.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/domain/service/ScheduleAPIService.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/command/infra/service/ScheduleInfraAPIService.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/query/application/controller/ScheduleQueryController.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/query/application/dto/DetailScheduleAndPlaceDTO.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/query/application/dto/LoadMyScheduleDTO.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/query/application/dto/MyScheduleResponseDTO.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/query/application/service/ScheduleQueryService.java
  src/main/java/com/ohgiraffers/adregamdi/schedule/query/infra/repository/ScheduleQueryRepository.java
  src/main/resources/static/images/airplane.png
  src/main/resources/static/images/images.jpg
  src/main/resources/static/images/volcano.png
  src/main/resources/static/images/volcanoBoom.png
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/schedule.html
Labels: ✨ Feature

#214 맵에 마커 찍기
  src/main/java/com/ohgiraffers/adregamdi/review/command/application/controller/ReviewController.java
  src/main/java/com/ohgiraffers/adregamdi/review/query/application/controller/ReviewQueryController.java
  src/main/java/com/ohgiraffers/adregamdi/review/query/application/service/ReviewQueryService.java
  src/main/resources/static/css/schedule.css
  src/main/resources/static/images/reviewImages/c665ae8c284e43f18c9f44be263abeba.png
  src/main/resources/static/js/kakaomap.js
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/schedule.html
Labels: ✨ Feature
